---
tasks:
  - name: Add repo
    become: true
    yum_repository:
      name: nginx
      description: NGINX repos
      baseurl: "https://nginx.org/packages/mainline/centos/8/x86_64/"
      gpgcheck: no
  - name: Nginx install
    become: true
    yum:
      name: nginx
      state: present
      notify: start-nginx
